version: "3.8"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${HOST_NGINX_PORT:-8080}:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/nginx-entrypoint.sh:/usr/local/bin/nginx-entrypoint.sh:ro
    entrypoint: ["/usr/local/bin/nginx-entrypoint.sh"]
    networks:
      - bg-net

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - PORT=${PORT}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "${HOST_BLUE_PORT:-8081}:${PORT}"
    networks:
      - bg-net

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - PORT=${PORT}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "${HOST_GREEN_PORT:-8082}:${PORT}"
    networks:
      - bg-net

networks:
  bg-net:
    driver: bridge
